# docker-compose.yml

version: '3'
services:
  flask-app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
    command: ["flask", "run", "--host=0.0.0.0"]

